# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"means": "00_core.ipynb",
         "stds": "00_core.ipynb",
         "open_img": "00_core.ipynb",
         "RsImage": "00_core.ipynb",
         "RsMask": "00_core.ipynb",
         "TrainTransform": "00_core.ipynb",
         "ValTransform": "00_core.ipynb",
         "aug_pipe": "00_core.ipynb",
         "val_pipe": "00_core.ipynb",
         "aug": "00_core.ipynb",
         "aug2": "00_core.ipynb",
         "VGGBlock": "01_model.ipynb",
         "NestedUNet": "01_model.ipynb",
         "UNet": "01_model.ipynb",
         "NestedUNet2": "01_model.ipynb",
         "OhemCrossEntropy": "01_model.ipynb",
         "ResNestedUNet": "01_model.ipynb",
         "aug_pipebig": "00_core.ipynb",
         "val_pipebig": "00_core.ipynb",
         "augb": "00_core.ipynb",
         "aug2b": "00_core.ipynb"}

modules = ["core.py",
           "model.py",
           "core2.py"]

doc_url = "https://robeson1010.github.io/RS/"

git_url = "https://github.com/robeson1010/RS/tree/master/"

def custom_doc_links(name): return None
